# Specify terminal colours in this file.
# This is the format used by termite
[colors]

# special
foreground      = "#ffffff"
foreground_bold = "#ffffff"
cursor          = "#ffffff"
background      = "#000000"

# black
color0  = "#000000"
color8  = "#818383"

# red
color1  = "#c23521"
color9  = "#fc391f"

# green
color2  = "#319630"
color10 = "#31e722"

# yellow
color3  = "#adad27"
color11 = "#eaec23"

# blue
color4  = "#5f46ec"
color12 = "#5833ff"

# magenta
color5  = "#d338d3"
color13 = "#f935ff"

# cyan
color6  = "#33bbc8"
color14 = "#14f0f0"

# white
color7  = "#cbcccd"
color15 = "#ffffff"
